language: java
jdk:
  - openjdk11
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - 'lxx3380@gmail.com'

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p depoly
  - mv freelec-springboot2-webservice.zip /deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings
    bucket: kukjun-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private 로